-- Persistent voxel mesh cache.
--
-- Stores processed vertex buffers in LOVE's save directory. GPU objects
-- themselves cannot be serialized, so a cached buffer is uploaded into a
-- fresh Mesh when its map becomes live again.
--
-- Cache files are local generated data. They contain no ROM, texture or
-- copyrighted game asset, only positions, atlas coordinates and shading
-- values generated by ChunkMesher.

local V = ...

local Voxel3D = V.require("Voxel3D")

local MeshDiskCache = {}

-- Bump this whenever the vertex format or terrain geometry rules change.
--
-- Including a build tag prevents older experimental files from being read
-- after this persistent-cache implementation changes.
MeshDiskCache.VERSION = "dsm-v2-dynamic-face-light"
MeshDiskCache.DIRECTORY = "dramatic_shape/mesh_cache/" ..
                          MeshDiskCache.VERSION

local HEADER = "DSMC1"
local STRIDE = 6 * 4
local MAX_VERTICES = 12000000
local UPLOAD_CHUNK = 65536

local function available()
  return love
     and love.filesystem
     and love.filesystem.read
     and love.filesystem.write
     and love.filesystem.createDirectory
     and love.graphics
     and love.graphics.newMesh
     and love.data
     and love.data.newByteData
end

MeshDiskCache.available = available

local function safeName(value)
  value = tostring(value or "unknown")
  value = value:gsub("[^%w_.%-]", "_")
  if value == "" then value = "unknown" end
  return value
end

local function pathFor(mapId, slot)
  return MeshDiskCache.DIRECTORY .. "/" ..
         safeName(mapId) .. "_" .. safeName(slot) .. ".dsm"
end

MeshDiskCache.pathFor = pathFor

local function parseFile(bytes)
  if type(bytes) ~= "string" then return nil end

  local first = bytes:find("\n", 1, true)
  if not first then return nil end

  local second = bytes:find("\n", first + 1, true)
  if not second then return nil end

  local magic = bytes:sub(1, first - 1)
  local count = tonumber(bytes:sub(first + 1, second - 1))

  if magic ~= HEADER then return nil end
  if not count or count < 0 or count > MAX_VERTICES then return nil end
  if count ~= math.floor(count) then return nil end

  local payload = bytes:sub(second + 1)
  local expected = count * STRIDE

  if #payload ~= expected then return nil end

  return count, payload
end

local function upload(count, payload)
  if count == 0 then return false end

  local ok, mesh = pcall(
    love.graphics.newMesh,
    Voxel3D.FORMAT,
    count,
    "triangles",
    "static"
  )

  if not ok or not mesh then return nil end

  local position = 0

  while position < count do
    local vertexCount = math.min(UPLOAD_CHUNK, count - position)
    local byteStart = position * STRIDE + 1
    local byteEnd = byteStart + vertexCount * STRIDE - 1
    local piece = payload:sub(byteStart, byteEnd)

    local dataOk, data = pcall(love.data.newByteData, piece)

    if not dataOk or not data then
      if mesh.release then pcall(mesh.release, mesh) end
      return nil
    end

    local setOk = pcall(
      mesh.setVertices,
      mesh,
      data,
      position + 1
    )

    if data.release then pcall(data.release, data) end

    if not setOk then
      if mesh.release then pcall(mesh.release, mesh) end
      return nil
    end

    position = position + vertexCount
  end

  return mesh
end

-- Returns:
--
--   mesh, true   valid cached mesh
--   false, true  valid cached empty mesh
--   nil, false   missing or invalid cache
function MeshDiskCache.load(mapId, slot)
  if not available() then return nil, false end

  local filename = pathFor(mapId, slot)
  local infoOk, info = pcall(love.filesystem.getInfo, filename)

  if not infoOk or not info then return nil, false end

  local readOk, bytes = pcall(love.filesystem.read, filename)

  if not readOk then return nil, false end

  local count, payload = parseFile(bytes)

  if not count then
    pcall(love.filesystem.remove, filename)
    return nil, false
  end

  local mesh = upload(count, payload)

  if count > 0 and not mesh then
    pcall(love.filesystem.remove, filename)
    return nil, false
  end

  return mesh, true
end

function MeshDiskCache.store(mapId, slot, count, payload)
  if not available() then return false end
  if type(count) ~= "number" then return false end

  count = math.floor(count)

  if count < 0 or count > MAX_VERTICES then return false end

  if count == 0 then
    payload = ""
  elseif type(payload) ~= "string" or #payload ~= count * STRIDE then
    return false
  end

  local dirOk = pcall(
    love.filesystem.createDirectory,
    MeshDiskCache.DIRECTORY
  )

  if not dirOk then return false end

  local filename = pathFor(mapId, slot)
  local bytes = HEADER .. "\n" .. tostring(count) .. "\n" .. payload

  local writeOk, result = pcall(
    love.filesystem.write,
    filename,
    bytes
  )

  return writeOk and result and true or false
end

function MeshDiskCache.invalidate(mapId)
  if not available() then return end

  local listOk, files = pcall(
    love.filesystem.getDirectoryItems,
    MeshDiskCache.DIRECTORY
  )

  if not listOk or type(files) ~= "table" then return end

  local prefix = safeName(mapId) .. "_"

  for _, name in ipairs(files) do
    if name:sub(1, #prefix) == prefix and name:sub(-4) == ".dsm" then
      pcall(
        love.filesystem.remove,
        MeshDiskCache.DIRECTORY .. "/" .. name
      )
    end
  end
end

function MeshDiskCache.clear()
  if not available() then return end

  local listOk, files = pcall(
    love.filesystem.getDirectoryItems,
    MeshDiskCache.DIRECTORY
  )

  if not listOk or type(files) ~= "table" then return end

  for _, name in ipairs(files) do
    if name:sub(-4) == ".dsm" then
      pcall(
        love.filesystem.remove,
        MeshDiskCache.DIRECTORY .. "/" .. name
      )
    end
  end
end

return MeshDiskCache
